name: .NET

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.png'

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack SmokeMe
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack SmokeMe/SmokeMe.csproj --configuration Release --no-build
    - name: Pack SmokeMe.AspNetCore
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack SmokeMe.AspNetCore/SmokeMe.AspNetCore.csproj --configuration Release --no-build
    - name: Upload SmokeMe NuGet
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: smokeme-nupkg
        path: SmokeMe/bin/Release/*.nupkg
    - name: Upload SmokeMe.AspNetCore NuGet
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: smokeme-aspnetcore-nupkg
        path: SmokeMe.AspNetCore/bin/Release/*.nupkg
